version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: subsmanager_postgres
    environment:
      POSTGRES_USER: subsmanager
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subsmanager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: subsmanager_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data: